---
title: "WSL Dropbox Install"
author: "sehoon.kwon#sangmyungUniv"
date: '2022 01 08 '
output:
  html_document:
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: false
---

## Dropbox : Headless install on a Windows Subsystem for Linux

윈도우 WSL (우분투) 명령문만으로 Dropbox 설치하기

-   윈도우 WSL은 GUI 없으므로 명령줄 입력만으로 Dropbox 설치

-   일반 사용자로서 sudo 명령으로 아래 명령들을 실행

-   참고: root로서 명령 실행하면 루트 디렉토리에 Dropbox 설치됨

    -   루트 디렉토리에 설치되면 일반 사용자 로그인시 Dropbox 사용 못함 



## 준비 단계

-   (재설치 등의 이유로) 이미 존재할 수 있는 해당 폴더를 제거

-   드랍박스 싸이트로부터 해당 파이썬 파일을 얻는다

-   모든 사용자에게 실행권한을 부여한다

```{bash, eval=F}
rm -rf ~/.dropbox-dist ~/.dropbox
wget -q -O ~/dropbox https://www.dropbox.com/download?dl=packages/dropbox.py
chmod a+x ~/dropbox
```

## 드랍박스 시작 실행

```{bash, eval=F}
~/dropbox start -i
```

-  실행하면 실행과정이 화면에 표시됨

  -  Starting Dropbox... 으로 시작
  
  -  마지막에 ...Done!

이어서 다음 두 명령을 실행해 본다 (필수적인지 여부는 잘 모르겠음)

```{bash, eval=F}
lsb_release -d
cat /proc/vmstat > /dev/null
```

-   `lsb_release -d`

    -   `Description: Ubuntu 20.04.3 LTS` 같은 결과물을 출력

-   `vmstat`

    -   하부 시스템의 리소스 사용 추이 관찰 위해 짧은 기간 단위로 실행

-   `/dev/null`

    -   출력 결과물을 삭제하는 대신에 화면/프린터 등에 표시되지 않도록 함

## 계정 연결

-   윈도우에서는 Dropbox 계정 로그인 상태 유지

-   WSL에서는 다음 명령을 실행

```{bash, eval=F}
~/dropbox start
```

-   명령 실행 결과로 화면 표시 URL 주소로 접속하여 계정 연결

    -   미리 윈도우에서 Dropbox 계정에 로그인 상태 유지
    
    -   WSL에서 `~/dropbox start` 실행

      *   화면 마지막에 웹 연결 주소 표시

    -   접속 방법 중 하나는 주소 복사해 윈도우에서 웹브라우저 주소창 입력

    -   윈도우에서 해당 주소 접속되면 기존계정 연결 여부 확인

## 정상 작동 확인

-   마지막으로 잘 작동되는지 확인하기 위해 다음 명령을 하나씩 실행해 본다

```{bash, eval=F}
~/dropbox status
~/dropbox stop
~/dropbox start
cd ~/Drobox
```

-   `~/dropbox status` 실행하면 `Up to date` 표시 될 것이다

-   `stop / start` 해서 정상 작동 여부 확인

-   `cd ~/Dropbox` 후 테스트 디렉토리 추가 삭제 등을 통해 연동작동 점검

## 출처

[드랍박스 포럼에서 검색](https://www.dropboxforum.com/t5/Dropbox-installs-integrations/Headless-install-on-a-Windows-substem-for-Linux/td-p/365055/page/2)

## 주의

껐다 켜면 드랍박스가 자동으로 시작되지 못함

- 다음 명령을 실행해도 마찬가지임 ㅠㅠ 

```{bash, eval=F}
~/dropbox autostart y
~/dropbox start
```

WSL 시작때마다 위 명령을 실행해야 함 ㅠㅠ

배치 명령으로 그나마 간단히 시작 명령 실행

- 위 코드 두 줄을 다음과 같은 방법으로 bash 파일로 만들어 실행함

```{bash, eval=F}
echo "~/dropbox autostart y" > drboxstart.sh
echo "~/dropbox start" >> drboxstart.sh
```

- 배치 실행방법

```{bash, eval=F}
. drboxstart.sh
```
  * 여기서 `.` 은 `source` 줄임표현임
  * 적절히 tab 키 눌러서 타이핑 수고를 줄임

**End of Doc**